# ==================<Кнопки и поля, которые есть в бк MarathonBet>===================
EXIT_BUTTON_XPATH = '/html/body/div[11]/header/div[2]/div/div/div[1]/div[2]/a[4]'
USERNAME_FIELD_XPATH = '/html/body/div[11]/header/div[2]/div/div/div[1]/div[2]/div/div/div/div[1]/div/div/div/input'
PASSWORD_FIELD_XPATH = '/html/body/div[11]/header/div[2]/div/div/div[1]/div[2]/div/div/div/div[2]/div/div[1]/div/input'
SIGN_IN_BUTTON_XPATH = '/html/body/div[11]/header/div[2]/div/div/div[1]/div[2]/div/div/button/span'
CLOSE_BK_MESSAGE_BUTTON_CLASS = 'button.btn-cancel.no.simplemodal-close'
CLOSE_PROMO_MESSAGE_BUTTON_CLASS = 'v-icon.notranslate.prevent-page-leave-modal-button.v-icon--link.v-icon--auto-fill'
SEARCH_ICON_BUTTON_XPATH = '/html/body/div[11]/header/div[2]/div/div/div[2]/div[2]/div[2]'
SEARCH_FIELD_CLASS = 'search__input'
SEARCH_ENTER_BUTTON_XPATH = '/html/body/div[11]/header/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/button[1]'
SEARCH_SPORTS_TAB_BUTTON_XPATH = '/html/body/div[11]/div/div[3]/div/div/div[1]/div[1]/div[1]/div/div/div/div[3]/div[1]/div/button[3]'
EVENT_MORE_BUTTON_XPATH = '/html/body/div[11]/div/div[3]/div/div/div[1]/div[1]/div[1]/div/div/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/table/tbody/tr/td[2]/table/tbody/tr[2]/td'
STAKE_FIELD_XPATH = '/html/body/div[11]/div/div[3]/div/div/div[2]/div/div[1]/div/div[1]/div[7]/table/tbody/tr/td/div/div[1]/div[2]/table/tbody/tr/td[2]/table/tbody/tr[1]/td[3]/input'
STAKE_ACCEPT_BUTTON_XPATH = '/html/body/div[11]/div/div[3]/div/div/div[2]/div/div[1]/div/div[1]/div[7]/table/tbody/tr/td/div/table[2]/tbody/tr[1]/td[2]/span'
CATEGORY_CLASS = 'category-label-link'
ALL_MARKETS_BUTTON_FPATH = '/html/body/div[11]/div/div[3]/div/div/div[1]/div[1]/div[1]/div/div/div/div[3]/div[2]/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[1]/table/tbody/tr[1]/td[1]'
# ==================</Кнопки и поля, которые есть в бк MarathonBet>=================